name: DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t lab-17-03 .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan Docker Image
        run: trivy image --severity HIGH,CRITICAL -f json -o current.json lab-17-03

      - name: Compare vulnerabilities
        run: |
          if diff baseline.json current.json > /dev/null; then
            echo "No new vulnerabilities ✅"
          else
            echo "New vulnerabilities detected ❌"
            exit 1
           fi

      - name : Count Vulnerabilities
        run: |
          cat current.json | grep | "VulnerabilityID" | wc -l

